//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource_fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Social.Services.Resources.SharedResource.fr-FR", typeof(SharedResource_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, votre session a expiré, veuillez vous reconnecter !.
        /// </summary>
        public static string _401eror {
            get {
                return ResourceManager.GetString("401eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been Deleted
        ///Le compte a été supprimé.
        /// </summary>
        public static string AccounthasbeenDeleted {
            get {
                return ResourceManager.GetString("AccounthasbeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajoutée.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les jours sont obligatoires.
        /// </summary>
        public static string AllDayIsRequired {
            get {
                return ResourceManager.GetString("AllDayIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nombre de participants ne doit pas être inférieur à 2.
        /// </summary>
        public static string AttendeesNumbershouldnotbelessthan2 {
            get {
                return ResourceManager.GetString("AttendeesNumbershouldnotbelessthan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;ajouter plus de.
        /// </summary>
        public static string CanNotAddMoreThan {
            get {
                return ResourceManager.GetString("CanNotAddMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classement requis.
        /// </summary>
        public static string CategoryIsRequired {
            get {
                return ResourceManager.GetString("CategoryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les détails de la caisse sont obligatoires.
        /// </summary>
        public static string CheckOutDetailsIsRequired {
            get {
                return ResourceManager.GetString("CheckOutDetailsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, veuillez vérifier votre e-mail ou votre mot de passe !.
        /// </summary>
        public static string checkyourE_mailorpassword_ {
            get {
                return ResourceManager.GetString("checkyourE-mailorpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, le code que vous avez entré est incorrect.
        /// </summary>
        public static string codeincorrect {
            get {
                return ResourceManager.GetString("codeincorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, le code que vous avez entré n&apos;est plus valide !.
        /// </summary>
        public static string codeinvalid {
            get {
                return ResourceManager.GetString("codeinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code a été envoyé avec succès.
        /// </summary>
        public static string codesentsuccessfully {
            get {
                return ResourceManager.GetString("codesentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat Date is required.
        /// </summary>
        public static string CreatDateisrequired {
            get {
                return ResourceManager.GetString("CreatDateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps de création requis.
        /// </summary>
        public static string CreatedTimeIsRequired {
            get {
                return ResourceManager.GetString("CreatedTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description is must Not more than 150 characters..
        /// </summary>
        public static string descriptionismustNotmorethan150characters_ {
            get {
                return ResourceManager.GetString("descriptionismustNotmorethan150characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptif obligatoire.
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complété.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Désolé, l&apos;e-mail existe déjà.
        /// </summary>
        public static string emailexists {
            get {
                return ResourceManager.GetString("emailexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, l&apos;e-mail n&apos;a pas encore été confirmé !.
        /// </summary>
        public static string emailhasnotconfirmed {
            get {
                return ResourceManager.GetString("emailhasnotconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, l&apos;email est incorrect !.
        /// </summary>
        public static string emailincorrect {
            get {
                return ResourceManager.GetString("emailincorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données d&apos;événement requises.
        /// </summary>
        public static string EventDataReqired {
            get {
                return ResourceManager.GetString("EventDataReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de l&apos;événement ne doit pas être dans le passé et pas après un an à partir de maintenant..
        /// </summary>
        public static string EventdatemustNotinthepast {
            get {
                return ResourceManager.GetString("EventdatemustNotinthepast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La limite supérieure pour la description de l&apos;événement est.
        /// </summary>
        public static string EventDetailsDescriptionMaxLengthIs {
            get {
                return ResourceManager.GetString("EventDetailsDescriptionMaxLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La description minimale de l&apos;événement est.
        /// </summary>
        public static string EventDetailsDescriptionMinLengthIs {
            get {
                return ResourceManager.GetString("EventDetailsDescriptionMinLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الحدث مطلوبه.
        /// </summary>
        public static string EventImageIsRequired {
            get {
                return ResourceManager.GetString("EventImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de début de l&apos;événement ne doit pas être antérieure à la date de fin de l&apos;événement.
        /// </summary>
        public static string EventstartdatemustNotolderthanEventenddate {
            get {
                return ResourceManager.GetString("EventstartdatemustNotolderthanEventenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de début de l&apos;événement ne doit pas être antérieure à l&apos;heure de fin de l&apos;événement.
        /// </summary>
        public static string EventstarttimemustNotolderthanEventendtime {
            get {
                return ResourceManager.GetString("EventstarttimemustNotolderthanEventendtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La limite supérieure du titre de l&apos;événement est.
        /// </summary>
        public static string EventTitleMaxLengthIs {
            get {
                return ResourceManager.GetString("EventTitleMaxLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le titre minimum de l&apos;événement est.
        /// </summary>
        public static string EventTitleMinLengthIs {
            get {
                return ResourceManager.GetString("EventTitleMinLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ISActive {
            get {
                return ResourceManager.GetString("ISActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier Json est vide.
        /// </summary>
        public static string JsonFileIsEmpty {
            get {
                return ResourceManager.GetString("JsonFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier Json est requis.
        /// </summary>
        public static string JsonFileIsReqired {
            get {
                return ResourceManager.GetString("JsonFileIsReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;emplacement est requis.
        /// </summary>
        public static string LocationsIsRequired {
            get {
                return ResourceManager.GetString("LocationsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;e-mail a été confirmé avec succès.
        /// </summary>
        public static string mailconfirmed {
            get {
                return ResourceManager.GetString("mailconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La période maximale autorisée pour l&apos;événement est d&apos;un mois.
        /// </summary>
        public static string Maximumallowedeventperiod {
            get {
                return ResourceManager.GetString("Maximumallowedeventperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir le nouveau mot de passe !.
        /// </summary>
        public static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas ajouté.
        /// </summary>
        public static string NotAdded {
            get {
                return ResourceManager.GetString("NotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe a été changé avec succès.
        /// </summary>
        public static string Passwordchangedsuccessfully {
            get {
                return ResourceManager.GetString("Passwordchangedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ du mot de passe est vide, il doit avoir une valeur.
        /// </summary>
        public static string Passwordfieldisemptyitismusthavevalue {
            get {
                return ResourceManager.GetString("Passwordfieldisemptyitismusthavevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit avoir plus de 8 caractères et moins de 32 caractères.
        /// </summary>
        public static string Passwordmusthavemorethan8charactersandlessthan32characters {
            get {
                return ResourceManager.GetString("Passwordmusthavemorethan8charactersandlessthan32characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe doit être une combinaison de lettres et de chiffres. Il doit comporter au moins une lettre et au moins un chiffre.
        /// </summary>
        public static string Passwordshouldbecombinationoflettersandnumbers_Itshouldhaveatleastoneletterandatleastonenumber {
            get {
                return ResourceManager.GetString("Passwordshouldbecombinationoflettersandnumbers.Itshouldhaveatleastoneletterandatl" +
                        "eastonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, le mot de passe ne doit pas être inférieur à 8 lettres ou chiffres !.
        /// </summary>
        public static string passwordvalid {
            get {
                return ResourceManager.GetString("passwordvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir le mot de passe actuel !.
        /// </summary>
        public static string Pleaseenterthecurrentpassword_ {
            get {
                return ResourceManager.GetString("Pleaseenterthecurrentpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir le nouveau mot de passe !.
        /// </summary>
        public static string Pleaseenterthenewpassword_ {
            get {
                return ResourceManager.GetString("Pleaseenterthenewpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez vous reconnecter.
        /// </summary>
        public static string Pleasere_login {
            get {
                return ResourceManager.GetString("Pleasere-login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner les participants pour votre événement.
        /// </summary>
        public static string PleaseSelectAttendeesForYourEvent {
            get {
                return ResourceManager.GetString("PleaseSelectAttendeesForYourEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Name.
        /// </summary>
        public static string ReasonName {
            get {
                return ResourceManager.GetString("ReasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , There are no places.
        /// </summary>
        public static string Sorry_Therearenoplaces {
            get {
                return ResourceManager.GetString("Sorry,Therearenoplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, il n&apos;y a pas de places !.
        /// </summary>
        public static string Sorry_Therearenoplaces_ {
            get {
                return ResourceManager.GetString("Sorry,Therearenoplaces!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les dates de début et de fin sont obligatoires.
        /// </summary>
        public static string StartAndEndDateIsRequired {
            get {
                return ResourceManager.GetString("StartAndEndDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure de début et de fin est requise.
        /// </summary>
        public static string StartAndEndTimeIsRequired {
            get {
                return ResourceManager.GetString("StartAndEndTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enregistré avec succès.
        /// </summary>
        public static string successfullyregistered {
            get {
                return ResourceManager.GetString("successfullyregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;événement ne vous appartient pas.
        /// </summary>
        public static string Theeventdoesnotbelongtoyou {
            get {
                return ResourceManager.GetString("Theeventdoesnotbelongtoyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cet événement existe déjà.
        /// </summary>
        public static string ThisEventAlreadyExists {
            get {
                return ResourceManager.GetString("ThisEventAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;adresse est obligatoire.
        /// </summary>
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le titre ne doit pas dépasser 32 caractères..
        /// </summary>
        public static string TitlemustNotmorethan32characters_ {
            get {
                return ResourceManager.GetString("TitlemustNotmorethan32characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre total requis.
        /// </summary>
        public static string TotalNumberIsRequired {
            get {
                return ResourceManager.GetString("TotalNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number must  not to be more than 5000.
        /// </summary>
        public static string TotalNumbermustnottobemorethan5000 {
            get {
                return ResourceManager.GetString("TotalNumbermustnottobemorethan5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vos données ont été modifiées avec succès !.
        /// </summary>
        public static string updateprofiledata {
            get {
                return ResourceManager.GetString("updateprofiledata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, cet utilisateur n&apos;existe pas !.
        /// </summary>
        public static string userdoesnotexist {
            get {
                return ResourceManager.GetString("userdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, l&apos;identifiant que vous avez entré n&apos;est plus valide !.
        /// </summary>
        public static string useridinvalid {
            get {
                return ResourceManager.GetString("useridinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé, le numéro de nom d&apos;utilisateur existe déjà !.
        /// </summary>
        public static string UserNameexists {
            get {
                return ResourceManager.GetString("UserNameexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le champ du nom d&apos;utilisateur est vide, il est obligatoire
        /// avoir de la valeur.
        /// </summary>
        public static string usernamefieldisemptyitismusthavevalue {
            get {
                return ResourceManager.GetString("usernamefieldisemptyitismusthavevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisateur doit avoir plus de 2 caractères et moins de 32 caractères.
        /// </summary>
        public static string Usernamemusthavemorethan2charactersandlessthan32characters {
            get {
                return ResourceManager.GetString("Usernamemusthavemorethan2charactersandlessthan32characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes déjà abonné.
        /// </summary>
        public static string Youarealreadysubscribed {
            get {
                return ResourceManager.GetString("Youarealreadysubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Blocked.
        /// </summary>
        public static string YouareBlocked {
            get {
                return ResourceManager.GetString("YouareBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;êtes pas abonné.
        /// </summary>
        public static string Youarenotsubscribed {
            get {
                return ResourceManager.GetString("Youarenotsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez réussi à quitter l&apos;événement.
        /// </summary>
        public static string YouhavesuccessfullyleaveEvent {
            get {
                return ResourceManager.GetString("YouhavesuccessfullyleaveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully Return to event.
        /// </summary>
        public static string YouhavesuccessfullyReturntoevent {
            get {
                return ResourceManager.GetString("YouhavesuccessfullyReturntoevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous vous êtes inscrit avec succès à l&apos;événement.
        /// </summary>
        public static string Youhavesuccessfullysubscribedtoevent {
            get {
                return ResourceManager.GetString("Youhavesuccessfullysubscribedtoevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre événement a été ajouté avec succès.
        /// </summary>
        public static string YourEventhasbeenAddedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenAddedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre événement a été supprimé avec succès.
        /// </summary>
        public static string YourEventhasbeenDeletedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenDeletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre événement a été mis à jour avec succès.
        /// </summary>
        public static string YourEventhasbeenUpdatedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenUpdatedsuccessfully", resourceCulture);
            }
        }
    }
}
