//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource_ar_EG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_ar_EG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Social.Services.Resources.SharedResource.ar-EG", typeof(SharedResource_ar_EG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تسجيل الدخول مرة أخرى!.
        /// </summary>
        public static string _401eror {
            get {
                return ResourceManager.GetString("401eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الحساب.
        /// </summary>
        public static string AccounthasbeenDeleted {
            get {
                return ResourceManager.GetString("AccounthasbeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمة الإضافه.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السن.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل الأيام مطلوبه.
        /// </summary>
        public static string AllDayIsRequired {
            get {
                return ResourceManager.GetString("AllDayIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر المسموج به في البحث.
        /// </summary>
        public static string allowedagefiltering {
            get {
                return ResourceManager.GetString("allowedagefiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسافه المسموح بها في البحث.
        /// </summary>
        public static string alloweddistancefiltering {
            get {
                return ResourceManager.GetString("alloweddistancefiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسافه لاظهار  المستخدمين .
        /// </summary>
        public static string allowedDistanceShowNearbyAccountsInFeed {
            get {
                return ResourceManager.GetString("allowedDistanceShowNearbyAccountsInFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسافه المسموحه لاظهار الاحداث علي الخريطه.
        /// </summary>
        public static string alloweddistanceshowNearbyeventsonmap {
            get {
                return ResourceManager.GetString("alloweddistanceshowNearbyeventsonmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمر المستخدم المسموح .
        /// </summary>
        public static string alloweduserage {
            get {
                return ResourceManager.GetString("alloweduserage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسجل من قبل.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعدادات .
        /// </summary>
        public static string AppConfigration {
            get {
                return ResourceManager.GetString("AppConfigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يقل عدد الحاضرين عن 2.
        /// </summary>
        public static string AttendeesNumbershouldnotbelessthan2 {
            get {
                return ResourceManager.GetString("AttendeesNumbershouldnotbelessthan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحضور.
        /// </summary>
        public static string AttendsCount {
            get {
                return ResourceManager.GetString("AttendsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الإضافه أكثر من.
        /// </summary>
        public static string CanNotAddMoreThan {
            get {
                return ResourceManager.GetString("CanNotAddMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف مطلوب.
        /// </summary>
        public static string CategoryIsRequired {
            get {
                return ResourceManager.GetString("CategoryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الدفع مطلوبه.
        /// </summary>
        public static string CheckOutDetailsIsRequired {
            get {
                return ResourceManager.GetString("CheckOutDetailsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، يرجى التحقق من البريد الإلكتروني أو كلمة المرور الخاصة بك!.
        /// </summary>
        public static string checkyourE_mailorpassword_ {
            get {
                return ResourceManager.GetString("checkyourE-mailorpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينه.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، الرمز الذي أدخلته غير صحيح.
        /// </summary>
        public static string codeincorrect {
            get {
                return ResourceManager.GetString("codeincorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، الرمز الذي أدخلته غير صالح الآن!.
        /// </summary>
        public static string codeinvalid {
            get {
                return ResourceManager.GetString("codeinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال الرمز بنجاح.
        /// </summary>
        public static string codesentsuccessfully {
            get {
                return ResourceManager.GetString("codesentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللون.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الاعدادات.
        /// </summary>
        public static string ConfigrationName {
            get {
                return ResourceManager.GetString("ConfigrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحه التحكم.
        /// </summary>
        public static string controlpanal {
            get {
                return ResourceManager.GetString("controlpanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدوله.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانشاء مطلوب.
        /// </summary>
        public static string CreatDateisrequired {
            get {
                return ResourceManager.GetString("CreatDateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الإنشاء مطلوب.
        /// </summary>
        public static string CreatedTimeIsRequired {
            get {
                return ResourceManager.GetString("CreatedTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يزيد الوصف عن 150 حرفًا..
        /// </summary>
        public static string descriptionismustNotmorethan150characters_ {
            get {
                return ResourceManager.GetString("descriptionismustNotmorethan150characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف مطلوب.
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العرض.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الترتيب.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسافه لاظهار الاحداث القريبه.
        /// </summary>
        public static string DistanceShowNearbyEvents {
            get {
                return ResourceManager.GetString("DistanceShowNearbyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل اعدادات التطبيق.
        /// </summary>
        public static string editappconfigration {
            get {
                return ResourceManager.GetString("editappconfigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، البريد الإلكتروني موجود بالفعل.
        /// </summary>
        public static string emailexists {
            get {
                return ResourceManager.GetString("emailexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، لم يتم تأكيد البريد الإلكتروني بعد!.
        /// </summary>
        public static string emailhasnotconfirmed {
            get {
                return ResourceManager.GetString("emailhasnotconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، البريد الإلكتروني غير صحيح!.
        /// </summary>
        public static string emailincorrect {
            get {
                return ResourceManager.GetString("emailincorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني مطلوب.
        /// </summary>
        public static string Emailisrequired {
            get {
                return ResourceManager.GetString("Emailisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحدث.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئات الحدث.
        /// </summary>
        public static string EventCategories {
            get {
                return ResourceManager.GetString("EventCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئه الحدث.
        /// </summary>
        public static string EventCategory {
            get {
                return ResourceManager.GetString("EventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد انشاء الاحداث للمسخدم.
        /// </summary>
        public static string EventCreation {
            get {
                return ResourceManager.GetString("EventCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث.
        /// </summary>
        public static string EventData {
            get {
                return ResourceManager.GetString("EventData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب بيانات الحدث.
        /// </summary>
        public static string EventDataReqired {
            get {
                return ResourceManager.GetString("EventDataReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يكون تاريخ الحدث في الماضي وليس بعد عام واحد من الآن..
        /// </summary>
        public static string EventdatemustNotinthepast {
            get {
                return ResourceManager.GetString("EventdatemustNotinthepast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد احرف وصف الحدث.
        /// </summary>
        public static string Eventdetailsdescription {
            get {
                return ResourceManager.GetString("Eventdetailsdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأعلى لوصف الحدث هو.
        /// </summary>
        public static string EventDetailsDescriptionMaxLengthIs {
            get {
                return ResourceManager.GetString("EventDetailsDescriptionMaxLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأدنى لوصف الحدث هو.
        /// </summary>
        public static string EventDetailsDescriptionMinLengthIs {
            get {
                return ResourceManager.GetString("EventDetailsDescriptionMinLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة الحدث مطلوبه.
        /// </summary>
        public static string EventImageIsRequired {
            get {
                return ResourceManager.GetString("EventImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يكون تاريخ بدء الحدث أقدم من تاريخ انتهاء الحدث.
        /// </summary>
        public static string EventstartdatemustNotolderthanEventenddate {
            get {
                return ResourceManager.GetString("EventstartdatemustNotolderthanEventenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يكون وقت بدء الحدث أقدم من وقت انتهاء الحدث.
        /// </summary>
        public static string EventstarttimemustNotolderthanEventendtime {
            get {
                return ResourceManager.GetString("EventstarttimemustNotolderthanEventendtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الحدث.
        /// </summary>
        public static string EventTilte {
            get {
                return ResourceManager.GetString("EventTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الحدث (س).
        /// </summary>
        public static string EventTimeValidation {
            get {
                return ResourceManager.GetString("EventTimeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأعلى لعنوان الحدث هو.
        /// </summary>
        public static string EventTitleMaxLengthIs {
            get {
                return ResourceManager.GetString("EventTitleMaxLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأدنى لعنوان الحدث هو.
        /// </summary>
        public static string EventTitleMinLengthIs {
            get {
                return ResourceManager.GetString("EventTitleMinLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحدث.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع الحدث.
        /// </summary>
        public static string EventTypeLists {
            get {
                return ResourceManager.GetString("EventTypeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم جوجل.
        /// </summary>
        public static string GoogleName {
            get {
                return ResourceManager.GetString("GoogleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسيه.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم غير صحيح.
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشط.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف فارغ.
        /// </summary>
        public static string JsonFileIsEmpty {
            get {
                return ResourceManager.GetString("JsonFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف مطلوب.
        /// </summary>
        public static string JsonFileIsReqired {
            get {
                return ResourceManager.GetString("JsonFileIsReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغه.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكان مطلوب.
        /// </summary>
        public static string LocationsIsRequired {
            get {
                return ResourceManager.GetString("LocationsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تأكيد البريد الإلكتروني بنجاح.
        /// </summary>
        public static string mailconfirmed {
            get {
                return ResourceManager.GetString("mailconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقصي عدد.
        /// </summary>
        public static string MaxCount {
            get {
                return ResourceManager.GetString("MaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى لفترة الحدث المسموح بها هو شهر واحد.
        /// </summary>
        public static string Maximumallowedeventperiod {
            get {
                return ResourceManager.GetString("Maximumallowedeventperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقل عدد.
        /// </summary>
        public static string MinCount {
            get {
                return ResourceManager.GetString("MinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال كلمة المرور الجديدة!.
        /// </summary>
        public static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تتم الإضافه.
        /// </summary>
        public static string NotAdded {
            get {
                return ResourceManager.GetString("NotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد الكتروني غير صحيح.
        /// </summary>
        public static string NotValidEmail {
            get {
                return ResourceManager.GetString("NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم يجب ان يكون اكبر من {0}.
        /// </summary>
        public static string NumberMoreThan {
            get {
                return ResourceManager.GetString("NumberMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمه المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الارقام في كلمه المرور.
        /// </summary>
        public static string passwordallowednumbers {
            get {
                return ResourceManager.GetString("passwordallowednumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغير كلمه السر.
        /// </summary>
        public static string Passwordchangedsuccessfully {
            get {
                return ResourceManager.GetString("Passwordchangedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمه السر مطلوبه.
        /// </summary>
        public static string Passwordfieldisemptyitismusthavevalue {
            get {
                return ResourceManager.GetString("Passwordfieldisemptyitismusthavevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمه المرور مطلوب.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد احرف كلمة المرور.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تحتوي كلمة المرور على أكثر من 8 أحرف وأقل من 32 حرفًا.
        /// </summary>
        public static string Passwordmusthavemorethan8charactersandlessthan32characters {
            get {
                return ResourceManager.GetString("Passwordmusthavemorethan8charactersandlessthan32characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تتكون كلمة المرور من أحرف وأرقام ، ويجب أن تحتوي على حرف واحد على الأقل ورقم واحد على الأقل.
        /// </summary>
        public static string Passwordshouldbecombinationoflettersandnumbers_Itshouldhaveatleastoneletterandatleastonenumber {
            get {
                return ResourceManager.GetString("Passwordshouldbecombinationoflettersandnumbers.Itshouldhaveatleastoneletterandatl" +
                        "eastonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحروف المميزة في كلمه المرور.
        /// </summary>
        public static string passwordspecialcharacters {
            get {
                return ResourceManager.GetString("passwordspecialcharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرًا ، يجب ألا تقل كلمة المرور عن 8 أحرف أو أرقام!.
        /// </summary>
        public static string passwordvalid {
            get {
                return ResourceManager.GetString("passwordvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  من فضلك ادخل كلمه  الحاليه.
        /// </summary>
        public static string Pleaseenterthecurrentpassword_ {
            get {
                return ResourceManager.GetString("Pleaseenterthecurrentpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ادخل كلمه السر الجديده.
        /// </summary>
        public static string Pleaseenterthenewpassword_ {
            get {
                return ResourceManager.GetString("Pleaseenterthenewpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك سجل دخول.
        /// </summary>
        public static string Pleasere_login {
            get {
                return ResourceManager.GetString("Pleasere-login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تحديد الحاضرين لهذا الحدث الخاص بك.
        /// </summary>
        public static string PleaseSelectAttendeesForYourEvent {
            get {
                return ResourceManager.GetString("PleaseSelectAttendeesForYourEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصص.
        /// </summary>
        public static string Privtekey {
            get {
                return ResourceManager.GetString("Privtekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال اشعارات.
        /// </summary>
        public static string PushNotfication {
            get {
                return ResourceManager.GetString("PushNotfication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string ReasonName {
            get {
                return ResourceManager.GetString("ReasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب الشكوي.
        /// </summary>
        public static string ReportReason {
            get {
                return ResourceManager.GetString("ReportReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسباب الشكاوي.
        /// </summary>
        public static string ReportReasons {
            get {
                return ResourceManager.GetString("ReportReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر .
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، لا توجد أماكن.
        /// </summary>
        public static string Sorry_Therearenoplaces {
            get {
                return ResourceManager.GetString("Sorry,Therearenoplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، لا توجد أماكن!.
        /// </summary>
        public static string Sorry_Therearenoplaces_ {
            get {
                return ResourceManager.GetString("Sorry,Therearenoplaces!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البادايه والنهايه مطلوب.
        /// </summary>
        public static string StartAndEndDateIsRequired {
            get {
                return ResourceManager.GetString("StartAndEndDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت البدايه والنهايه مطلوب.
        /// </summary>
        public static string StartAndEndTimeIsRequired {
            get {
                return ResourceManager.GetString("StartAndEndTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجلت بنجاح.
        /// </summary>
        public static string successfullyregistered {
            get {
                return ResourceManager.GetString("successfullyregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإرسال بنجاح.
        /// </summary>
        public static string SuccessfulSent {
            get {
                return ResourceManager.GetString("SuccessfulSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحدث لا يخصك.
        /// </summary>
        public static string Theeventdoesnotbelongtoyou {
            get {
                return ResourceManager.GetString("Theeventdoesnotbelongtoyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحدث موجود من قبل.
        /// </summary>
        public static string ThisEventAlreadyExists {
            get {
                return ResourceManager.GetString("ThisEventAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان مطلوب.
        /// </summary>
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يزيد العنوان عن 32 حرفًا..
        /// </summary>
        public static string TitlemustNotmorethan32characters_ {
            get {
                return ResourceManager.GetString("TitlemustNotmorethan32characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد الإجمالي مطلوب.
        /// </summary>
        public static string TotalNumberIsRequired {
            get {
                return ResourceManager.GetString("TotalNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يزيد العدد الإجمالي عن 5000.
        /// </summary>
        public static string TotalNumbermustnottobemorethan5000 {
            get {
                return ResourceManager.GetString("TotalNumbermustnottobemorethan5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحديدث بنجاح.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير بياناتك بنجاح!.
        /// </summary>
        public static string updateprofiledata {
            get {
                return ResourceManager.GetString("updateprofiledata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد العلامات المسموحه للمستخدم.
        /// </summary>
        public static string UserAllowedTags {
            get {
                return ResourceManager.GetString("UserAllowedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد احرف نبذه عن المستخدم.
        /// </summary>
        public static string UserBioLength {
            get {
                return ResourceManager.GetString("UserBioLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، هذا المستخدم غير موجود!.
        /// </summary>
        public static string userdoesnotexist {
            get {
                return ResourceManager.GetString("userdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، معرف المستخدم الذي أدخلته غير صالح الآن!.
        /// </summary>
        public static string useridinvalid {
            get {
                return ResourceManager.GetString("useridinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، رقم اسم المستخدم موجود بالفعل!.
        /// </summary>
        public static string UserNameexists {
            get {
                return ResourceManager.GetString("UserNameexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم مطلوب.
        /// </summary>
        public static string usernamefieldisemptyitismusthavevalue {
            get {
                return ResourceManager.GetString("usernamefieldisemptyitismusthavevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد احرف اسم المستخدم.
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يحتوي اسم المستخدم على أكثر من حرفين وأقل من 32 حرفًا.
        /// </summary>
        public static string Usernamemusthavemorethan2charactersandlessthan32characters {
            get {
                return ResourceManager.GetString("Usernamemusthavemorethan2charactersandlessthan32characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انت مشترك اصلا.
        /// </summary>
        public static string Youarealreadysubscribed {
            get {
                return ResourceManager.GetString("Youarealreadysubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنت محظورة.
        /// </summary>
        public static string YouareBlocked {
            get {
                return ResourceManager.GetString("YouareBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انت لست مشترك في الحدث.
        /// </summary>
        public static string Youarenotsubscribed {
            get {
                return ResourceManager.GetString("Youarenotsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد نجحت في مغادرة الحدث.
        /// </summary>
        public static string YouhavesuccessfullyleaveEvent {
            get {
                return ResourceManager.GetString("YouhavesuccessfullyleaveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد نجحت في العودة إلى الحدث.
        /// </summary>
        public static string YouhavesuccessfullyReturntoevent {
            get {
                return ResourceManager.GetString("YouhavesuccessfullyReturntoevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد اشتركت بنجاح في الحدث.
        /// </summary>
        public static string Youhavesuccessfullysubscribedtoevent {
            get {
                return ResourceManager.GetString("Youhavesuccessfullysubscribedtoevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة حدثك بنجاح.
        /// </summary>
        public static string YourEventhasbeenAddedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenAddedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الحدث الخاص بك بنجاح.
        /// </summary>
        public static string YourEventhasbeenDeletedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenDeletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت  تعديل حدثك بنجاح.
        /// </summary>
        public static string YourEventhasbeenUpdatedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenUpdatedsuccessfully", resourceCulture);
            }
        }
    }
}
