//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Social.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Social.Services.Resources.SharedResource.en-US", typeof(SharedResource_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry your session is expired, Please login again!.
        /// </summary>
        public static string _401eror {
            get {
                return ResourceManager.GetString("401eror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been Deleted.
        /// </summary>
        public static string AccounthasbeenDeleted {
            get {
                return ResourceManager.GetString("AccounthasbeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day Is Required.
        /// </summary>
        public static string AllDayIsRequired {
            get {
                return ResourceManager.GetString("AllDayIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allowed age filtering.
        /// </summary>
        public static string allowedagefiltering {
            get {
                return ResourceManager.GetString("allowedagefiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allowed distance filtering.
        /// </summary>
        public static string alloweddistancefiltering {
            get {
                return ResourceManager.GetString("alloweddistancefiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allowed distance show near by accounts InFeed.
        /// </summary>
        public static string allowedDistanceShowNearbyAccountsInFeed {
            get {
                return ResourceManager.GetString("allowedDistanceShowNearbyAccountsInFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allowed distance  show Near by events on map.
        /// </summary>
        public static string alloweddistanceshowNearbyeventsonmap {
            get {
                return ResourceManager.GetString("alloweddistanceshowNearbyeventsonmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allowed user age.
        /// </summary>
        public static string alloweduserage {
            get {
                return ResourceManager.GetString("alloweduserage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlreadyExist.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app Configuration.
        /// </summary>
        public static string AppConfigration {
            get {
                return ResourceManager.GetString("AppConfigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees Number should not be less than 2.
        /// </summary>
        public static string AttendeesNumbershouldnotbelessthan2 {
            get {
                return ResourceManager.GetString("AttendeesNumbershouldnotbelessthan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttendsCount.
        /// </summary>
        public static string AttendsCount {
            get {
                return ResourceManager.GetString("AttendsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Add More Than.
        /// </summary>
        public static string CanNotAddMoreThan {
            get {
                return ResourceManager.GetString("CanNotAddMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Is Required.
        /// </summary>
        public static string CategoryIsRequired {
            get {
                return ResourceManager.GetString("CategoryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Details Is Required.
        /// </summary>
        public static string CheckOutDetailsIsRequired {
            get {
                return ResourceManager.GetString("CheckOutDetailsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, please check your E-mail or password!.
        /// </summary>
        public static string checkyourE_mailorpassword_ {
            get {
                return ResourceManager.GetString("checkyourE-mailorpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the code you entered is incorrect.
        /// </summary>
        public static string codeincorrect {
            get {
                return ResourceManager.GetString("codeincorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the code you entered is now invalid!.
        /// </summary>
        public static string codeinvalid {
            get {
                return ResourceManager.GetString("codeinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has been sent successfully.
        /// </summary>
        public static string codesentsuccessfully {
            get {
                return ResourceManager.GetString("codesentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name.
        /// </summary>
        public static string ConfigrationName {
            get {
                return ResourceManager.GetString("ConfigrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panal.
        /// </summary>
        public static string controlpanale {
            get {
                return ResourceManager.GetString("controlpanale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat Date is required.
        /// </summary>
        public static string CreatDateisrequired {
            get {
                return ResourceManager.GetString("CreatDateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time Is Required.
        /// </summary>
        public static string CreatedTimeIsRequired {
            get {
                return ResourceManager.GetString("CreatedTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must not exceed 150 characters..
        /// </summary>
        public static string descriptionismustNotmorethan150characters_ {
            get {
                return ResourceManager.GetString("descriptionismustNotmorethan150characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Is Required.
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Show Near by Events.
        /// </summary>
        public static string DistanceShowNearbyEvents {
            get {
                return ResourceManager.GetString("DistanceShowNearbyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was completed.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit application configration.
        /// </summary>
        public static string editappconfigration {
            get {
                return ResourceManager.GetString("editappconfigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !Sorry, the email already exists.
        /// </summary>
        public static string emailexists {
            get {
                return ResourceManager.GetString("emailexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this email is not verified, please go to your mail inbox to verify it then login.
        /// </summary>
        public static string emailhasnotconfirmed {
            get {
                return ResourceManager.GetString("emailhasnotconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the email is incorrect !.
        /// </summary>
        public static string emailincorrect {
            get {
                return ResourceManager.GetString("emailincorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string Emailisrequired {
            get {
                return ResourceManager.GetString("Emailisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Categories.
        /// </summary>
        public static string EventCategories {
            get {
                return ResourceManager.GetString("EventCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Category.
        /// </summary>
        public static string EventCategory {
            get {
                return ResourceManager.GetString("EventCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event creation limite.
        /// </summary>
        public static string EventCreation {
            get {
                return ResourceManager.GetString("EventCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Data.
        /// </summary>
        public static string EventData {
            get {
                return ResourceManager.GetString("EventData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Data Reqired.
        /// </summary>
        public static string EventDataReqired {
            get {
                return ResourceManager.GetString("EventDataReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date must Not in the past and Not after one year from now..
        /// </summary>
        public static string EventdatemustNotinthepast {
            get {
                return ResourceManager.GetString("EventdatemustNotinthepast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event details description.
        /// </summary>
        public static string Eventdetailsdescription {
            get {
                return ResourceManager.GetString("Eventdetailsdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Details Description Max Length Is.
        /// </summary>
        public static string EventDetailsDescriptionMaxLengthIs {
            get {
                return ResourceManager.GetString("EventDetailsDescriptionMaxLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Details Description Min Length Is.
        /// </summary>
        public static string EventDetailsDescriptionMinLengthIs {
            get {
                return ResourceManager.GetString("EventDetailsDescriptionMinLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Image Is Required.
        /// </summary>
        public static string EventImageIsRequired {
            get {
                return ResourceManager.GetString("EventImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start date must Not older than Event end date.
        /// </summary>
        public static string EventstartdatemustNotolderthanEventenddate {
            get {
                return ResourceManager.GetString("EventstartdatemustNotolderthanEventenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start time must Not older than Event end time.
        /// </summary>
        public static string EventstarttimemustNotolderthanEventendtime {
            get {
                return ResourceManager.GetString("EventstarttimemustNotolderthanEventendtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Tilte.
        /// </summary>
        public static string EventTilte {
            get {
                return ResourceManager.GetString("EventTilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event time validation (H).
        /// </summary>
        public static string EventTimeValidation {
            get {
                return ResourceManager.GetString("EventTimeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Title Max Length is.
        /// </summary>
        public static string EventTitleMaxLengthIs {
            get {
                return ResourceManager.GetString("EventTitleMaxLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event  Title Min Length is.
        /// </summary>
        public static string EventTitleMinLengthIs {
            get {
                return ResourceManager.GetString("EventTitleMinLengthIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Type.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Types.
        /// </summary>
        public static string EventTypeLists {
            get {
                return ResourceManager.GetString("EventTypeLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoogleName.
        /// </summary>
        public static string GoogleName {
            get {
                return ResourceManager.GetString("GoogleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am.
        /// </summary>
        public static string Iam {
            get {
                return ResourceManager.GetString("Iam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I enjoy.
        /// </summary>
        public static string Ienjoy {
            get {
                return ResourceManager.GetString("Ienjoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json File Is Empty.
        /// </summary>
        public static string JsonFileIsEmpty {
            get {
                return ResourceManager.GetString("JsonFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Json File Is Reqired.
        /// </summary>
        public static string JsonFileIsReqired {
            get {
                return ResourceManager.GetString("JsonFileIsReqired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations Is Required.
        /// </summary>
        public static string LocationsIsRequired {
            get {
                return ResourceManager.GetString("LocationsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email has been confirmed successfully.
        /// </summary>
        public static string mailconfirmed {
            get {
                return ResourceManager.GetString("mailconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum count.
        /// </summary>
        public static string MaxCount {
            get {
                return ResourceManager.GetString("MaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed event period is one month.
        /// </summary>
        public static string Maximumallowedeventperiod {
            get {
                return ResourceManager.GetString("Maximumallowedeventperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum count.
        /// </summary>
        public static string MinCount {
            get {
                return ResourceManager.GetString("MinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new password !.
        /// </summary>
        public static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Added.
        /// </summary>
        public static string NotAdded {
            get {
                return ResourceManager.GetString("NotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Valid Email.
        /// </summary>
        public static string NotValidEmail {
            get {
                return ResourceManager.GetString("NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number must be more than {0}.
        /// </summary>
        public static string NumberMoreThan {
            get {
                return ResourceManager.GetString("NumberMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password allowed numbers.
        /// </summary>
        public static string passwordallowednumbers {
            get {
                return ResourceManager.GetString("passwordallowednumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string Passwordchangedsuccessfully {
            get {
                return ResourceManager.GetString("Passwordchangedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is empty it is must have value.
        /// </summary>
        public static string Passwordfieldisemptyitismusthavevalue {
            get {
                return ResourceManager.GetString("Passwordfieldisemptyitismusthavevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password length.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have more than 8 characters and less than 32 characters.
        /// </summary>
        public static string Passwordmusthavemorethan8charactersandlessthan32characters {
            get {
                return ResourceManager.GetString("Passwordmusthavemorethan8charactersandlessthan32characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be combination of letters and numbers .Its hould have at leastone letter and at least one number.
        /// </summary>
        public static string Passwordshouldbecombinationoflettersandnumbers_Itshouldhaveatleastoneletterandatleastonenumber {
            get {
                return ResourceManager.GetString("Passwordshouldbecombinationoflettersandnumbers.Itshouldhaveatleastoneletterandatl" +
                        "eastonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password special characters.
        /// </summary>
        public static string passwordspecialcharacters {
            get {
                return ResourceManager.GetString("passwordspecialcharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the password must not be less than 8 letters or numbers!.
        /// </summary>
        public static string passwordvalid {
            get {
                return ResourceManager.GetString("passwordvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the current password!.
        /// </summary>
        public static string Pleaseenterthecurrentpassword_ {
            get {
                return ResourceManager.GetString("Pleaseenterthecurrentpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new password!.
        /// </summary>
        public static string Pleaseenterthenewpassword_ {
            get {
                return ResourceManager.GetString("Pleaseenterthenewpassword!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-login.
        /// </summary>
        public static string Pleasere_login {
            get {
                return ResourceManager.GetString("Pleasere-login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select attendees for your event.
        /// </summary>
        public static string PleaseSelectAttendeesForYourEvent {
            get {
                return ResourceManager.GetString("PleaseSelectAttendeesForYourEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privte key.
        /// </summary>
        public static string Privtekey {
            get {
                return ResourceManager.GetString("Privtekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notfication.
        /// </summary>
        public static string PushNotfication {
            get {
                return ResourceManager.GetString("PushNotfication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Reason.
        /// </summary>
        public static string ReportReason {
            get {
                return ResourceManager.GetString("ReportReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Reasons.
        /// </summary>
        public static string ReportReasons {
            get {
                return ResourceManager.GetString("ReportReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , There are no places.
        /// </summary>
        public static string Sorry_Therearenoplaces {
            get {
                return ResourceManager.GetString("Sorry,Therearenoplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , There are no places!.
        /// </summary>
        public static string Sorry_Therearenoplaces_ {
            get {
                return ResourceManager.GetString("Sorry,Therearenoplaces!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start And End Date Is Required.
        /// </summary>
        public static string StartAndEndDateIsRequired {
            get {
                return ResourceManager.GetString("StartAndEndDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start And End Time Is Required.
        /// </summary>
        public static string StartAndEndTimeIsRequired {
            get {
                return ResourceManager.GetString("StartAndEndTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully registered.
        /// </summary>
        public static string successfullyregistered {
            get {
                return ResourceManager.GetString("successfullyregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Sent.
        /// </summary>
        public static string SuccessfulSent {
            get {
                return ResourceManager.GetString("SuccessfulSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event does not belong to you.
        /// </summary>
        public static string Theeventdoesnotbelongtoyou {
            get {
                return ResourceManager.GetString("Theeventdoesnotbelongtoyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Event Already Exists.
        /// </summary>
        public static string ThisEventAlreadyExists {
            get {
                return ResourceManager.GetString("ThisEventAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Is Required.
        /// </summary>
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must not exceed 32 characters..
        /// </summary>
        public static string TitlemustNotmorethan32characters_ {
            get {
                return ResourceManager.GetString("TitlemustNotmorethan32characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number Is Required.
        /// </summary>
        public static string TotalNumberIsRequired {
            get {
                return ResourceManager.GetString("TotalNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number must  not to be more than 5000.
        /// </summary>
        public static string TotalNumbermustnottobemorethan5000 {
            get {
                return ResourceManager.GetString("TotalNumbermustnottobemorethan5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data has been changed successfully !.
        /// </summary>
        public static string updateprofiledata {
            get {
                return ResourceManager.GetString("updateprofiledata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user allowed tags.
        /// </summary>
        public static string UserAllowedTags {
            get {
                return ResourceManager.GetString("UserAllowedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user bio length.
        /// </summary>
        public static string UserBioLength {
            get {
                return ResourceManager.GetString("UserBioLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this user does not exist!.
        /// </summary>
        public static string userdoesnotexist {
            get {
                return ResourceManager.GetString("userdoesnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the userid you entered is now invalid!.
        /// </summary>
        public static string useridinvalid {
            get {
                return ResourceManager.GetString("useridinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the UserName number already exists !.
        /// </summary>
        public static string UserNameexists {
            get {
                return ResourceManager.GetString("UserNameexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name field is empty it is must have value.
        /// </summary>
        public static string usernamefieldisemptyitismusthavevalue {
            get {
                return ResourceManager.GetString("usernamefieldisemptyitismusthavevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name length.
        /// </summary>
        public static string UserNameLength {
            get {
                return ResourceManager.GetString("UserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 2 characters and at most 32 characters..
        /// </summary>
        public static string Usernamemusthavemorethan2charactersandlessthan32characters {
            get {
                return ResourceManager.GetString("Usernamemusthavemorethan2charactersandlessthan32characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Reports.
        /// </summary>
        public static string UserReports {
            get {
                return ResourceManager.GetString("UserReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already subscribed.
        /// </summary>
        public static string Youarealreadysubscribed {
            get {
                return ResourceManager.GetString("Youarealreadysubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Blocked.
        /// </summary>
        public static string YouareBlocked {
            get {
                return ResourceManager.GetString("YouareBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not subscribed.
        /// </summary>
        public static string Youarenotsubscribed {
            get {
                return ResourceManager.GetString("Youarenotsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You have successfully left this event.
        /// </summary>
        public static string YouhavesuccessfullyleaveEvent {
            get {
                return ResourceManager.GetString("YouhavesuccessfullyleaveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully Return to event.
        /// </summary>
        public static string YouhavesuccessfullyReturntoevent {
            get {
                return ResourceManager.GetString("YouhavesuccessfullyReturntoevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully subscribed to event.
        /// </summary>
        public static string Youhavesuccessfullysubscribedtoevent {
            get {
                return ResourceManager.GetString("Youhavesuccessfullysubscribedtoevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Event has been Added successfully.
        /// </summary>
        public static string YourEventhasbeenAddedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenAddedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Event has been Deleted successfully.
        /// </summary>
        public static string YourEventhasbeenDeletedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenDeletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Event has been Updated successfully.
        /// </summary>
        public static string YourEventhasbeenUpdatedsuccessfully {
            get {
                return ResourceManager.GetString("YourEventhasbeenUpdatedsuccessfully", resourceCulture);
            }
        }
    }
}
